name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper dh-python python3-all python3-setuptools devscripts
        
    - name: Build Debian package
      run: |
        # Set version from tag or use default
        VERSION=${GITHUB_REF#refs/tags/v}
        if [ "$VERSION" = "$GITHUB_REF" ]; then
          VERSION="0.1.0"
        fi
        
        # Set email for changelog
        export DEBEMAIL="myself@mariusv.com"
        export DEBFULLNAME="Marius Voila"
        
        # Only update changelog if version differs
        CURRENT_VERSION=$(dpkg-parsechangelog -S Version)
        if [ "$CURRENT_VERSION" != "$VERSION" ]; then
          dch -v ${VERSION} -D unstable "Release version ${VERSION}"
        fi
        
        # Build the package
        dpkg-buildpackage -us -uc -b
        
        # Move the built package
        mv ../cloudflare-ddns-updater_*.deb .
        
    - name: Test package installation
      run: |
        sudo dpkg -i cloudflare-ddns-updater_*.deb || sudo apt-get install -f -y
        # Verify files are installed
        test -f /usr/bin/cloudflare-ddns
        test -f /lib/systemd/system/cloudflare-ddns.service
        test -f /lib/systemd/system/cloudflare-ddns.timer
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: cloudflare-ddns-updater_*.deb
        generate_release_notes: true
        
    - name: Build container image
      run: |
        # Create a simple Dockerfile
        cat > Dockerfile << 'EOF'
        FROM debian:bookworm-slim
        
        RUN apt-get update && \
            apt-get install -y python3 python3-requests systemd && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*
        
        COPY cloudflare-ddns-updater_*.deb /tmp/
        RUN dpkg -i /tmp/cloudflare-ddns-updater_*.deb && \
            rm /tmp/cloudflare-ddns-updater_*.deb
        
        # Create a wrapper script for container use
        RUN echo '#!/bin/bash\nif [ ! -f /etc/cloudflare-ddns/config.json ]; then\n  echo "Error: /etc/cloudflare-ddns/config.json not found"\n  echo "Mount your config file to /etc/cloudflare-ddns/config.json"\n  exit 1\nfi\nexec /usr/bin/cloudflare-ddns' > /usr/local/bin/docker-entrypoint.sh && \
            chmod +x /usr/local/bin/docker-entrypoint.sh
        
        VOLUME ["/etc/cloudflare-ddns", "/var/cache/cloudflare-ddns"]
        
        ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
        EOF
        
        # Build the image
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
        
    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push container image
      if: github.event_name != 'pull_request'
      run: |
        # Also tag with version if this is a tag
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
        fi
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest